CREATE TABLE IF NOT EXISTS `smurfportal` (
  `id` bigint(20) NOT NULL COMMENT 'индекс',
  `guid` char(35) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'уникальный номер портала',
  `lat` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'latitude',
  `lng` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'langitude',
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Нименование портала',
  `approved` double DEFAULT NULL COMMENT 'Дата создания портала',
  `curr_owner` text COLLATE utf8_unicode_ci COMMENT 'текущий владелец',
  `level` int(11) DEFAULT NULL COMMENT 'Уровень портала',
  `resCount` int(11) DEFAULT NULL COMMENT 'Кол-во установленных резов',
  `dateCapture` double DEFAULT NULL COMMENT 'дата захвата',
  `timeUpdated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `mode1owner` text COLLATE utf8_unicode_ci,
  `mode1name` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mode1rarity` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mode2owner` text COLLATE utf8_unicode_ci,
  `mode2name` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mode2rarity` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mode3owner` text COLLATE utf8_unicode_ci,
  `mode3name` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mode3rarity` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mode4owner` text COLLATE utf8_unicode_ci,
  `mode4name` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mode4rarity` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `res1owner` text COLLATE utf8_unicode_ci,
  `res1energy` int(11) DEFAULT NULL,
  `res1level` int(11) DEFAULT NULL,
  `res2owner` text COLLATE utf8_unicode_ci,
  `res2energy` int(11) DEFAULT NULL,
  `res2level` int(11) DEFAULT NULL,
  `res3owner` text CHARACTER SET utf32 COLLATE utf32_unicode_ci,
  `res3energy` int(11) DEFAULT NULL,
  `res3level` int(11) DEFAULT NULL,
  `res4owner` text COLLATE utf8_unicode_ci,
  `res4energy` int(11) DEFAULT NULL,
  `res4level` int(11) DEFAULT NULL,
  `res5owner` text COLLATE utf8_unicode_ci,
  `res5energy` int(11) DEFAULT NULL,
  `res5level` int(11) DEFAULT NULL,
  `res6owner` text COLLATE utf8_unicode_ci,
  `res6energy` int(11) DEFAULT NULL,
  `res6level` int(11) DEFAULT NULL,
  `res7owner` text CHARACTER SET utf32 COLLATE utf32_unicode_ci,
  `res7energy` int(11) DEFAULT NULL,
  `res7level` int(11) DEFAULT NULL,
  `res8owner` text COLLATE utf8_unicode_ci,
  `res8energy` int(11) DEFAULT NULL,
  `res8level` int(11) DEFAULT NULL,
  `image` text COLLATE utf8_unicode_ci
) ENGINE=InnoDB AUTO_INCREMENT=444239 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Словарь порталов';

ALTER TABLE `smurfportal`
ADD PRIMARY KEY (`id`),
ADD UNIQUE KEY `id` (`id`),
ADD UNIQUE KEY `guid_2` (`guid`),
ADD KEY `latIndex` (`lat`),
ADD KEY `lngIndex` (`lng`),
ADD KEY `ownerIndex` (`curr_owner`(255));